version: '3.4'

services:
  geozonereferential.interface:
    image: ${DOCKER_REGISTRY}geozonereferentialinterface
    build:
      context: .
      dockerfile: GeoZoneReferential.Interface/Dockerfile
