using Microsoft.EntityFrameworkCore.Migrations;
using System.Text;

namespace GeoZoneReferential.Infrastructure.Migrations
{
    public partial class Countries_Feed : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            string countriesRequest = @"
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AF', N'AFGHANISTAN', N'Afghanistan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AL', N'ALBANIA', N'Albania')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'DZ', N'ALGERIA', N'Algeria')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AS', N'AMERICAN SAMOA', N'American Samoa')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AD', N'ANDORRA', N'Andorra')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AO', N'ANGOLA', N'Angola')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AI', N'ANGUILLA', N'Anguilla')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AQ', N'ANTARCTICA', N'Antarctica')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AG', N'ANTIGUA AND BARBUDA', N'Antigua and Barbuda')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AR', N'ARGENTINA', N'Argentina')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AM', N'ARMENIA', N'Armenia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AW', N'ARUBA', N'Aruba')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AU', N'AUSTRALIA', N'Australia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AT', N'AUSTRIA', N'Austria')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AZ', N'AZERBAIJAN', N'Azerbaijan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BS', N'BAHAMAS', N'Bahamas')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BH', N'BAHRAIN', N'Bahrain')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BD', N'BANGLADESH', N'Bangladesh')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BB', N'BARBADOS', N'Barbados')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BY', N'BELARUS', N'Belarus')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BE', N'BELGIUM', N'Belgium')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BZ', N'BELIZE', N'Belize')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BJ', N'BENIN', N'Benin')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BM', N'BERMUDA', N'Bermuda')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BT', N'BHUTAN', N'Bhutan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BO', N'BOLIVIA', N'Bolivia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BA', N'BOSNIA AND HERZEGOVINA', N'Bosnia and Herzegovina')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BW', N'BOTSWANA', N'Botswana')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BV', N'BOUVET ISLAND', N'Bouvet Island')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BR', N'BRAZIL', N'Brazil')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'IO', N'BRITISH INDIAN OCEAN TERRITORY', N'British Indian Ocean Territory')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BN', N'BRUNEI DARUSSALAM', N'Brunei Darussalam')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BG', N'BULGARIA', N'Bulgaria')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BF', N'BURKINA FASO', N'Burkina Faso')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'BI', N'BURUNDI', N'Burundi')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KH', N'CAMBODIA', N'Cambodia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CM', N'CAMEROON', N'Cameroon')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CA', N'CANADA', N'Canada')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CV', N'CAPE VERDE', N'Cape Verde')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KY', N'CAYMAN ISLANDS', N'Cayman Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CF', N'CENTRAL AFRICAN REPUBLIC', N'Central African Republic')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TD', N'CHAD', N'Chad')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CL', N'CHILE', N'Chile')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CN', N'CHINA', N'China')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CX', N'CHRISTMAS ISLAND', N'Christmas Island')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CC', N'COCOS (KEELING) ISLANDS', N'Cocos (Keeling) Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CO', N'COLOMBIA', N'Colombia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KM', N'COMOROS', N'Comoros')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CG', N'CONGO', N'Congo')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CD', N'CONGO, THE DEMOCRATIC REPUBLIC OF THE', N'Congo, the Democratic Republic of the')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CK', N'COOK ISLANDS', N'Cook Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CR', N'COSTA RICA', N'Costa Rica')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CI', N'COTE D''IVOIRE', N'Cote D''Ivoire')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'HR', N'CROATIA', N'Croatia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CU', N'CUBA', N'Cuba')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CY', N'CYPRUS', N'Cyprus')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CZ', N'CZECH REPUBLIC', N'Czech Republic')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'DK', N'DENMARK', N'Denmark')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'DJ', N'DJIBOUTI', N'Djibouti')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'DM', N'DOMINICA', N'Dominica')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'DO', N'DOMINICAN REPUBLIC', N'Dominican Republic')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'EC', N'ECUADOR', N'Ecuador')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'EG', N'EGYPT', N'Egypt')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SV', N'EL SALVADOR', N'El Salvador')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GQ', N'EQUATORIAL GUINEA', N'Equatorial Guinea')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'ER', N'ERITREA', N'Eritrea')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'EE', N'ESTONIA', N'Estonia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'ET', N'ETHIOPIA', N'Ethiopia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'FK', N'FALKLAND ISLANDS (MALVINAS)', N'Falkland Islands (Malvinas)')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'FO', N'FAROE ISLANDS', N'Faroe Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'FJ', N'FIJI', N'Fiji')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'FI', N'FINLAND', N'Finland')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'FR', N'FRANCE', N'France')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GF', N'FRENCH GUIANA', N'French Guiana')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PF', N'FRENCH POLYNESIA', N'French Polynesia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TF', N'FRENCH SOUTHERN TERRITORIES', N'French Southern Territories')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GA', N'GABON', N'Gabon')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GM', N'GAMBIA', N'Gambia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GE', N'GEORGIA', N'Georgia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'DE', N'GERMANY', N'Germany')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GH', N'GHANA', N'Ghana')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GI', N'GIBRALTAR', N'Gibraltar')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GR', N'GREECE', N'Greece')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GL', N'GREENLAND', N'Greenland')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GD', N'GRENADA', N'Grenada')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GP', N'GUADELOUPE', N'Guadeloupe')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GU', N'GUAM', N'Guam')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GT', N'GUATEMALA', N'Guatemala')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GN', N'GUINEA', N'Guinea')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GW', N'GUINEA-BISSAU', N'Guinea-Bissau')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GY', N'GUYANA', N'Guyana')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'HT', N'HAITI', N'Haiti')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'HM', N'HEARD ISLAND AND MCDONALD ISLANDS', N'Heard Island and Mcdonald Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'VA', N'HOLY SEE (VATICAN CITY STATE)', N'Holy See (Vatican City State)')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'HN', N'HONDURAS', N'Honduras')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'HK', N'HONG KONG', N'Hong Kong')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'HU', N'HUNGARY', N'Hungary')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'IS', N'ICELAND', N'Iceland')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'IN', N'INDIA', N'India')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'ID', N'INDONESIA', N'Indonesia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'IR', N'IRAN, ISLAMIC REPUBLIC OF', N'Iran, Islamic Republic of')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'IQ', N'IRAQ', N'Iraq')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'IE', N'IRELAND', N'Ireland')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'IL', N'ISRAEL', N'Israel')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'IT', N'ITALY', N'Italy')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'JM', N'JAMAICA', N'Jamaica')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'JP', N'JAPAN', N'Japan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'JO', N'JORDAN', N'Jordan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KZ', N'KAZAKHSTAN', N'Kazakhstan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KE', N'KENYA', N'Kenya')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KI', N'KIRIBATI', N'Kiribati')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KP', N'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', N'Korea, Democratic People''s Republic of')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KR', N'KOREA, REPUBLIC OF', N'Korea, Republic of')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KW', N'KUWAIT', N'Kuwait')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KG', N'KYRGYZSTAN', N'Kyrgyzstan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LA', N'LAO PEOPLE''S DEMOCRATIC REPUBLIC', N'Lao People''s Democratic Republic')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LV', N'LATVIA', N'Latvia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LB', N'LEBANON', N'Lebanon')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LS', N'LESOTHO', N'Lesotho')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LR', N'LIBERIA', N'Liberia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LY', N'LIBYAN ARAB JAMAHIRIYA', N'Libyan Arab Jamahiriya')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LI', N'LIECHTENSTEIN', N'Liechtenstein')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LT', N'LITHUANIA', N'Lithuania')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LU', N'LUXEMBOURG', N'Luxembourg')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MO', N'MACAO', N'Macao')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MK', N'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', N'Macedonia, the Former Yugoslav Republic of')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MG', N'MADAGASCAR', N'Madagascar')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MW', N'MALAWI', N'Malawi')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MY', N'MALAYSIA', N'Malaysia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MV', N'MALDIVES', N'Maldives')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'ML', N'MALI', N'Mali')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MT', N'MALTA', N'Malta')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MH', N'MARSHALL ISLANDS', N'Marshall Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MQ', N'MARTINIQUE', N'Martinique')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MR', N'MAURITANIA', N'Mauritania')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MU', N'MAURITIUS', N'Mauritius')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'YT', N'MAYOTTE', N'Mayotte')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MX', N'MEXICO', N'Mexico')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'FM', N'MICRONESIA, FEDERATED STATES OF', N'Micronesia, Federated States of')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MD', N'MOLDOVA, REPUBLIC OF', N'Moldova, Republic of')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MC', N'MONACO', N'Monaco')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MN', N'MONGOLIA', N'Mongolia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MS', N'MONTSERRAT', N'Montserrat')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MA', N'MOROCCO', N'Morocco')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MZ', N'MOZAMBIQUE', N'Mozambique')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MM', N'MYANMAR', N'Myanmar')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NA', N'NAMIBIA', N'Namibia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NR', N'NAURU', N'Nauru')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NP', N'NEPAL', N'Nepal')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NL', N'NETHERLANDS', N'Netherlands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AN', N'NETHERLANDS ANTILLES', N'Netherlands Antilles')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NC', N'NEW CALEDONIA', N'New Caledonia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NZ', N'NEW ZEALAND', N'New Zealand')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NI', N'NICARAGUA', N'Nicaragua')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NE', N'NIGER', N'Niger')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NG', N'NIGERIA', N'Nigeria')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NU', N'NIUE', N'Niue')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NF', N'NORFOLK ISLAND', N'Norfolk Island')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'MP', N'NORTHERN MARIANA ISLANDS', N'Northern Mariana Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'NO', N'NORWAY', N'Norway')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'OM', N'OMAN', N'Oman')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PK', N'PAKISTAN', N'Pakistan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PW', N'PALAU', N'Palau')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PS', N'PALESTINIAN TERRITORY, OCCUPIED', N'Palestinian Territory, Occupied')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PA', N'PANAMA', N'Panama')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PG', N'PAPUA NEW GUINEA', N'Papua New Guinea')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PY', N'PARAGUAY', N'Paraguay')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PE', N'PERU', N'Peru')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PH', N'PHILIPPINES', N'Philippines')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PN', N'PITCAIRN', N'Pitcairn')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PL', N'POLAND', N'Poland')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PT', N'PORTUGAL', N'Portugal')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PR', N'PUERTO RICO', N'Puerto Rico')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'QA', N'QATAR', N'Qatar')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'RE', N'REUNION', N'Reunion')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'RO', N'ROMANIA', N'Romania')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'RU', N'RUSSIAN FEDERATION', N'Russian Federation')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'RW', N'RWANDA', N'Rwanda')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SH', N'SAINT HELENA', N'Saint Helena')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'KN', N'SAINT KITTS AND NEVIS', N'Saint Kitts and Nevis')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LC', N'SAINT LUCIA', N'Saint Lucia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'PM', N'SAINT PIERRE AND MIQUELON', N'Saint Pierre and Miquelon')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'VC', N'SAINT VINCENT AND THE GRENADINES', N'Saint Vincent and the Grenadines')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'WS', N'SAMOA', N'Samoa')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SM', N'SAN MARINO', N'San Marino')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'ST', N'SAO TOME AND PRINCIPE', N'Sao Tome and Principe')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SA', N'SAUDI ARABIA', N'Saudi Arabia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SN', N'SENEGAL', N'Senegal')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CS', N'SERBIA AND MONTENEGRO', N'Serbia and Montenegro')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SC', N'SEYCHELLES', N'Seychelles')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SL', N'SIERRA LEONE', N'Sierra Leone')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SG', N'SINGAPORE', N'Singapore')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SK', N'SLOVAKIA', N'Slovakia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SI', N'SLOVENIA', N'Slovenia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SB', N'SOLOMON ISLANDS', N'Solomon Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SO', N'SOMALIA', N'Somalia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'ZA', N'SOUTH AFRICA', N'South Africa')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GS', N'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', N'South Georgia and the South Sandwich Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'ES', N'SPAIN', N'Spain')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'LK', N'SRI LANKA', N'Sri Lanka')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SD', N'SUDAN', N'Sudan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SR', N'SURIWordingS42Standard', N'SuriWordingS42Standard')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SJ', N'SVALBARD AND JAN MAYEN', N'Svalbard and Jan Mayen')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SZ', N'SWAZILAND', N'Swaziland')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SE', N'SWEDEN', N'Sweden')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'CH', N'SWITZERLAND', N'Switzerland')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'SY', N'SYRIAN ARAB REPUBLIC', N'Syrian Arab Republic')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TW', N'TAIWAN, PROVINCE OF CHINA', N'Taiwan, Province of China')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TJ', N'TAJIKISTAN', N'Tajikistan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TZ', N'TANZANIA, UNITED REPUBLIC OF', N'Tanzania, United Republic of')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TH', N'THAILAND', N'Thailand')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TL', N'TIMOR-LESTE', N'Timor-Leste')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TG', N'TOGO', N'Togo')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TK', N'TOKELAU', N'Tokelau')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TO', N'TONGA', N'Tonga')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TT', N'TRINIDAD AND TOBAGO', N'Trinidad and Tobago')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TN', N'TUNISIA', N'Tunisia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TR', N'TURKEY', N'Turkey')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TM', N'TURKMENISTAN', N'Turkmenistan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TC', N'TURKS AND CAICOS ISLANDS', N'Turks and Caicos Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'TV', N'TUVALU', N'Tuvalu')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'UG', N'UGANDA', N'Uganda')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'UA', N'UKRAINE', N'Ukraine')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'AE', N'UNITED ARAB EMIRATES', N'United Arab Emirates')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'GB', N'UNITED KINGDOM', N'United Kingdom')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'US', N'UNITED STATES', N'United States')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'UM', N'UNITED STATES MINOR OUTLYING ISLANDS', N'United States Minor Outlying Islands')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'UY', N'URUGUAY', N'Uruguay')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'UZ', N'UZBEKISTAN', N'Uzbekistan')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'VU', N'VANUATU', N'Vanuatu')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'VE', N'VENEZUELA', N'Venezuela')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'VN', N'VIET NAM', N'Viet Nam')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'VG', N'VIRGIN ISLANDS, BRITISH', N'Virgin Islands, British')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'VI', N'VIRGIN ISLANDS, U.S.', N'Virgin Islands, U.s.')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'WF', N'WALLIS AND FUTUNA', N'Wallis and Futuna')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'EH', N'WESTERN SAHARA', N'Western Sahara')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'YE', N'YEMEN', N'Yemen')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'ZM', N'ZAMBIA', N'Zambia')
                INSERT [Countries] ([ISO3166A2Code], [WordingS42Standard], [Wording]) VALUES (N'ZW', N'ZIMBABWE', N'Zimbabwe')
            ";
                       
            migrationBuilder.Sql(countriesRequest);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE * FROM Countries");
        }
    }
}
